import 'package:rezepte/features/recipes/domain/models/recipe.dart';
import 'package:rezepte/features/recipes/domain/models/ingredient.dart';
import 'package:rezepte/features/recipes/domain/models/recipe_step.dart';

/// ~20 eingebaute deutsche Rezepte als Vorschläge und Inspiration
final List<Recipe> seedRecipes = [
  _recipe(
    id: 'seed-1',
    title: 'Spaghetti Bolognese',
    category: RecipeCategory.meat,
    tags: ['italienisch', 'Pasta', 'Klassiker'],
    prepTime: 15, cookTime: 45, servings: 4,
    ingredients: [
      _ing('Spaghetti', 500, 'g'),
      _ing('Hackfleisch (gemischt)', 400, 'g'),
      _ing('Zwiebel', 1, 'Stück'),
      _ing('Knoblauchzehe', 2, 'Stück'),
      _ing('Passata', 500, 'ml'),
      _ing('Tomatenmark', 2, 'EL'),
      _ing('Olivenöl', 2, 'EL'),
      _ing('Salz', null, null),
      _ing('Pfeffer', null, null),
      _ing('Oregano', 1, 'TL'),
      _ing('Parmesan', 50, 'g'),
    ],
    steps: [
      'Zwiebel und Knoblauch fein hacken.',
      'Olivenöl in einer Pfanne erhitzen, Hackfleisch anbraten und krümelig braten.',
      'Zwiebel und Knoblauch dazugeben, 2 Minuten mitbraten.',
      'Tomatenmark einrühren, kurz anrösten.',
      'Passata dazugeben, mit Salz, Pfeffer und Oregano würzen.',
      'Bei niedriger Hitze 30 Minuten köcheln lassen.',
      'Spaghetti nach Packungsanweisung kochen.',
      'Pasta mit Sauce servieren und Parmesan darüber reiben.',
    ],
  ),
  _recipe(
    id: 'seed-2',
    title: 'Gemüse-Curry mit Reis',
    category: RecipeCategory.vegan,
    tags: ['asiatisch', 'schnell', 'gesund'],
    prepTime: 10, cookTime: 20, servings: 4,
    ingredients: [
      _ing('Basmatireis', 300, 'g'),
      _ing('Kokosmilch', 400, 'ml'),
      _ing('Currypaste (rot)', 2, 'EL'),
      _ing('Paprika', 2, 'Stück'),
      _ing('Zucchini', 1, 'Stück'),
      _ing('Kichererbsen (Dose)', 1, 'Dose'),
      _ing('Spinat', 200, 'g'),
      _ing('Zwiebel', 1, 'Stück'),
      _ing('Knoblauchzehe', 2, 'Stück'),
      _ing('Ingwer', 1, 'TL'),
      _ing('Sojasauce', 1, 'EL'),
      _ing('Limettensaft', 1, 'EL'),
    ],
    steps: [
      'Reis nach Packungsanweisung kochen.',
      'Zwiebel, Knoblauch und Ingwer fein hacken.',
      'Paprika und Zucchini in Würfel schneiden.',
      'Öl in einem Wok erhitzen, Zwiebel, Knoblauch und Ingwer anbraten.',
      'Currypaste dazugeben und kurz anrösten.',
      'Gemüse dazugeben und 3 Minuten braten.',
      'Kokosmilch und abgetropfte Kichererbsen dazugeben, 10 Minuten köcheln.',
      'Spinat unterrühren, mit Sojasauce und Limettensaft abschmecken.',
      'Mit Reis servieren.',
    ],
  ),
  _recipe(
    id: 'seed-3',
    title: 'Lachs mit Ofengemüse',
    category: RecipeCategory.fish,
    tags: ['gesund', 'einfach', 'Ofen'],
    prepTime: 15, cookTime: 25, servings: 2,
    ingredients: [
      _ing('Lachsfilet', 2, 'Stück'),
      _ing('Kartoffeln', 400, 'g'),
      _ing('Brokkoli', 200, 'g'),
      _ing('Cherrytomaten', 200, 'g'),
      _ing('Olivenöl', 3, 'EL'),
      _ing('Zitrone', 1, 'Stück'),
      _ing('Knoblauchzehe', 2, 'Stück'),
      _ing('Salz', null, null),
      _ing('Pfeffer', null, null),
      _ing('Dill', 1, 'Bund'),
    ],
    steps: [
      'Ofen auf 200°C vorheizen.',
      'Kartoffeln in Würfel schneiden, Brokkoli in Röschen teilen.',
      'Gemüse mit Olivenöl, Salz und Pfeffer auf einem Blech verteilen.',
      '15 Minuten im Ofen backen.',
      'Lachs mit Zitronensaft beträufeln, würzen.',
      'Lachs zum Gemüse legen und weitere 12-15 Minuten backen.',
      'Mit frischem Dill garnieren.',
    ],
  ),
  _recipe(
    id: 'seed-4',
    title: 'Kartoffelsuppe',
    category: RecipeCategory.vegetarian,
    tags: ['deutsch', 'Suppe', 'Herbst', 'einfach'],
    prepTime: 15, cookTime: 25, servings: 4,
    ingredients: [
      _ing('Kartoffeln (mehlig)', 800, 'g'),
      _ing('Zwiebel', 1, 'Stück'),
      _ing('Lauch', 1, 'Stück'),
      _ing('Gemüsebrühe', 1, 'l'),
      _ing('Sahne', 100, 'ml'),
      _ing('Butter', 20, 'g'),
      _ing('Muskatnuss', 1, 'Prise'),
      _ing('Salz', null, null),
      _ing('Pfeffer', null, null),
    ],
    steps: [
      'Kartoffeln schälen und würfeln, Lauch in Ringe schneiden, Zwiebel hacken.',
      'Butter in einem Topf erhitzen, Zwiebel und Lauch andünsten.',
      'Kartoffeln dazugeben und mit Brühe auffüllen.',
      '20 Minuten kochen bis die Kartoffeln weich sind.',
      'Suppe teilweise pürieren (etwas stückig lassen).',
      'Sahne einrühren, mit Muskatnuss, Salz und Pfeffer abschmecken.',
    ],
  ),
  _recipe(
    id: 'seed-5',
    title: 'Hähnchen-Teriyaki mit Gemüse',
    category: RecipeCategory.meat,
    tags: ['asiatisch', 'schnell', 'Pfanne'],
    prepTime: 10, cookTime: 15, servings: 2,
    ingredients: [
      _ing('Hähnchenbrustfilet', 300, 'g'),
      _ing('Reis', 200, 'g'),
      _ing('Paprika', 1, 'Stück'),
      _ing('Brokkoli', 150, 'g'),
      _ing('Sojasauce', 3, 'EL'),
      _ing('Honig', 2, 'EL'),
      _ing('Knoblauchzehe', 1, 'Stück'),
      _ing('Ingwer', 1, 'TL'),
      _ing('Sesamöl', 1, 'EL'),
      _ing('Sesam', 1, 'EL'),
    ],
    steps: [
      'Reis kochen. Hähnchen in Streifen schneiden.',
      'Sojasauce, Honig, gepressten Knoblauch und Ingwer verrühren.',
      'Sesamöl in einer Pfanne erhitzen, Hähnchen anbraten.',
      'Gemüse dazugeben, 3-4 Minuten mitbraten.',
      'Teriyaki-Sauce darüber gießen, einkochen lassen.',
      'Mit Reis und Sesam servieren.',
    ],
  ),
  _recipe(
    id: 'seed-6',
    title: 'Caprese-Salat',
    category: RecipeCategory.vegetarian,
    tags: ['italienisch', 'schnell', 'Salat', 'Sommer'],
    prepTime: 10, cookTime: 0, servings: 2,
    ingredients: [
      _ing('Tomaten (reif)', 3, 'Stück'),
      _ing('Mozzarella', 250, 'g'),
      _ing('Basilikum', 1, 'Bund'),
      _ing('Olivenöl', 3, 'EL'),
      _ing('Balsamico-Essig', 1, 'EL'),
      _ing('Salz', null, null),
      _ing('Pfeffer', null, null),
    ],
    steps: [
      'Tomaten und Mozzarella in Scheiben schneiden.',
      'Abwechselnd auf einem Teller anrichten.',
      'Mit Basilikumblättern belegen.',
      'Olivenöl und Balsamico darüber träufeln, salzen und pfeffern.',
    ],
  ),
  _recipe(
    id: 'seed-7',
    title: 'Linsen-Dal',
    category: RecipeCategory.vegan,
    tags: ['indisch', 'gesund', 'günstig'],
    prepTime: 10, cookTime: 30, servings: 4,
    ingredients: [
      _ing('Rote Linsen', 250, 'g'),
      _ing('Kokosmilch', 200, 'ml'),
      _ing('Zwiebel', 1, 'Stück'),
      _ing('Knoblauchzehe', 2, 'Stück'),
      _ing('Ingwer', 2, 'TL'),
      _ing('Kurkuma', 1, 'TL'),
      _ing('Kreuzkümmel', 1, 'TL'),
      _ing('Tomaten (gehackt, Dose)', 1, 'Dose'),
      _ing('Gemüsebrühe', 400, 'ml'),
      _ing('Koriander', 1, 'Bund'),
      _ing('Naan-Brot', 4, 'Stück'),
    ],
    steps: [
      'Linsen waschen. Zwiebel, Knoblauch und Ingwer fein hacken.',
      'Öl erhitzen, Zwiebel glasig dünsten.',
      'Knoblauch, Ingwer und Gewürze 1 Minute mitbraten.',
      'Linsen, Tomaten und Brühe dazugeben.',
      '20 Minuten köcheln bis die Linsen weich sind.',
      'Kokosmilch einrühren, abschmecken.',
      'Mit Koriander und Naan-Brot servieren.',
    ],
  ),
  _recipe(
    id: 'seed-8',
    title: 'Fischstäbchen mit Kartoffelpüree',
    category: RecipeCategory.fish,
    tags: ['deutsch', 'Kinder', 'einfach'],
    prepTime: 15, cookTime: 20, servings: 4,
    ingredients: [
      _ing('Kabeljaufilet', 400, 'g'),
      _ing('Paniermehl', 100, 'g'),
      _ing('Ei', 2, 'Stück'),
      _ing('Mehl', 50, 'g'),
      _ing('Kartoffeln', 800, 'g'),
      _ing('Milch', 100, 'ml'),
      _ing('Butter', 30, 'g'),
      _ing('Erbsen (TK)', 200, 'g'),
      _ing('Öl (zum Braten)', 4, 'EL'),
    ],
    steps: [
      'Kartoffeln schälen, kochen, mit Milch und Butter stampfen.',
      'Fisch in Stäbchen schneiden.',
      'Mehl, verquirltes Ei und Paniermehl bereitstellen.',
      'Fisch panieren: Mehl, Ei, Paniermehl.',
      'In Öl von jeder Seite 3-4 Minuten goldbraun braten.',
      'Erbsen nach Packungsanweisung kochen.',
      'Mit Kartoffelpüree und Erbsen servieren.',
    ],
  ),
  _recipe(
    id: 'seed-9',
    title: 'Griechischer Bauernsalat',
    category: RecipeCategory.vegetarian,
    tags: ['griechisch', 'Salat', 'schnell', 'Sommer'],
    prepTime: 15, cookTime: 0, servings: 2,
    ingredients: [
      _ing('Tomaten', 3, 'Stück'),
      _ing('Gurke', 1, 'Stück'),
      _ing('Paprika (rot)', 1, 'Stück'),
      _ing('Rote Zwiebel', 1, 'Stück'),
      _ing('Feta', 200, 'g'),
      _ing('Oliven (Kalamata)', 80, 'g'),
      _ing('Olivenöl', 4, 'EL'),
      _ing('Rotweinessig', 2, 'EL'),
      _ing('Oregano', 1, 'TL'),
    ],
    steps: [
      'Tomaten, Gurke und Paprika in grobe Stücke schneiden.',
      'Zwiebel in Ringe schneiden.',
      'Alles in eine Schüssel geben.',
      'Feta darüber bröseln, Oliven dazugeben.',
      'Olivenöl und Essig darüber geben, mit Oregano bestreuen.',
    ],
  ),
  _recipe(
    id: 'seed-10',
    title: 'Rindergulasch',
    category: RecipeCategory.meat,
    tags: ['deutsch', 'Eintopf', 'Herbst', 'deftig'],
    prepTime: 20, cookTime: 120, servings: 4,
    ingredients: [
      _ing('Rindfleisch (Gulasch)', 600, 'g'),
      _ing('Zwiebeln', 3, 'Stück'),
      _ing('Paprika (rot)', 2, 'Stück'),
      _ing('Tomatenmark', 2, 'EL'),
      _ing('Paprikapulver (edelsüß)', 2, 'EL'),
      _ing('Rinderbrühe', 500, 'ml'),
      _ing('Öl', 3, 'EL'),
      _ing('Salz', null, null),
      _ing('Pfeffer', null, null),
      _ing('Lorbeerblatt', 2, 'Stück'),
      _ing('Schmand', 100, 'g'),
      _ing('Spätzle', 400, 'g'),
    ],
    steps: [
      'Fleisch in Würfel schneiden, Zwiebeln grob hacken, Paprika würfeln.',
      'Öl in einem schweren Topf erhitzen, Fleisch portionsweise scharf anbraten.',
      'Zwiebeln dazugeben, glasig dünsten.',
      'Tomatenmark und Paprikapulver einrühren, kurz anrösten.',
      'Mit Brühe ablöschen, Paprika und Lorbeer dazugeben.',
      'Zugedeckt bei niedriger Hitze 1,5-2 Stunden schmoren.',
      'Spätzle nach Packungsanweisung kochen.',
      'Gulasch mit Schmand verfeinern und mit Spätzle servieren.',
    ],
  ),
  _recipe(
    id: 'seed-11',
    title: 'Pad Thai',
    category: RecipeCategory.vegetarian,
    tags: ['thailändisch', 'asiatisch', 'Nudeln'],
    prepTime: 15, cookTime: 10, servings: 2,
    ingredients: [
      _ing('Reisnudeln', 200, 'g'),
      _ing('Tofu', 200, 'g'),
      _ing('Ei', 2, 'Stück'),
      _ing('Sojasprossen', 100, 'g'),
      _ing('Frühlingszwiebeln', 3, 'Stück'),
      _ing('Erdnüsse', 30, 'g'),
      _ing('Limette', 1, 'Stück'),
      _ing('Sojasauce', 2, 'EL'),
      _ing('Fischsauce', 1, 'EL'),
      _ing('Zucker', 1, 'EL'),
      _ing('Tamarindenpaste', 1, 'EL'),
      _ing('Öl', 2, 'EL'),
    ],
    steps: [
      'Reisnudeln nach Packungsanweisung einweichen.',
      'Sauce mischen: Sojasauce, Fischsauce, Zucker, Tamarindenpaste.',
      'Tofu würfeln und in Öl goldbraun braten.',
      'Eier verquirlen und als Rührei dazugeben.',
      'Nudeln und Sauce dazugeben, alles vermengen.',
      'Sojasprossen und Frühlingszwiebeln unterheben.',
      'Mit gehackten Erdnüssen und Limettenspalten servieren.',
    ],
  ),
  _recipe(
    id: 'seed-12',
    title: 'Ofenkartoffeln mit Kräuterquark',
    category: RecipeCategory.vegetarian,
    tags: ['deutsch', 'einfach', 'günstig', 'Ofen'],
    prepTime: 10, cookTime: 45, servings: 2,
    ingredients: [
      _ing('Große Kartoffeln', 4, 'Stück'),
      _ing('Quark', 250, 'g'),
      _ing('Schnittlauch', 1, 'Bund'),
      _ing('Petersilie', 1, 'Bund'),
      _ing('Knoblauchzehe', 1, 'Stück'),
      _ing('Salz', null, null),
      _ing('Pfeffer', null, null),
      _ing('Olivenöl', 2, 'EL'),
    ],
    steps: [
      'Ofen auf 200°C vorheizen.',
      'Kartoffeln waschen, kreuzweise einschneiden.',
      'Mit Olivenöl einreiben und salzen.',
      '45 Minuten im Ofen backen.',
      'Kräuter fein hacken, Knoblauch pressen.',
      'Alles mit Quark verrühren, würzen.',
      'Kartoffeln aufdrücken und mit Kräuterquark füllen.',
    ],
  ),
  _recipe(
    id: 'seed-13',
    title: 'Garnelen-Scampi mit Knoblauch',
    category: RecipeCategory.fish,
    tags: ['mediterran', 'schnell', 'elegante'],
    prepTime: 10, cookTime: 10, servings: 2,
    ingredients: [
      _ing('Garnelen (geschält)', 300, 'g'),
      _ing('Knoblauchzehen', 4, 'Stück'),
      _ing('Olivenöl', 4, 'EL'),
      _ing('Weißwein', 100, 'ml'),
      _ing('Petersilie', 1, 'Bund'),
      _ing('Chilischote', 1, 'Stück'),
      _ing('Baguette', 1, 'Stück'),
      _ing('Zitrone', 1, 'Stück'),
      _ing('Salz', null, null),
    ],
    steps: [
      'Knoblauch in dünne Scheiben schneiden, Chili fein hacken.',
      'Olivenöl in einer Pfanne erhitzen, Knoblauch und Chili kurz anschwitzen.',
      'Garnelen dazugeben, 2 Minuten von jeder Seite braten.',
      'Mit Weißwein ablöschen, 2 Minuten einkochen.',
      'Gehackte Petersilie und Zitronensaft unterrühren.',
      'Mit Baguette servieren.',
    ],
  ),
  _recipe(
    id: 'seed-14',
    title: 'Shakshuka',
    category: RecipeCategory.vegetarian,
    tags: ['orientalisch', 'Frühstück', 'schnell'],
    prepTime: 10, cookTime: 20, servings: 2,
    ingredients: [
      _ing('Eier', 4, 'Stück'),
      _ing('Passata', 400, 'ml'),
      _ing('Paprika (rot)', 1, 'Stück'),
      _ing('Zwiebel', 1, 'Stück'),
      _ing('Knoblauchzehe', 2, 'Stück'),
      _ing('Kreuzkümmel', 1, 'TL'),
      _ing('Paprikapulver', 1, 'TL'),
      _ing('Feta', 50, 'g'),
      _ing('Koriander', 1, 'Bund'),
      _ing('Brot', 4, 'Stück'),
    ],
    steps: [
      'Zwiebel und Paprika würfeln, Knoblauch hacken.',
      'In Olivenöl andünsten, Gewürze dazugeben.',
      'Passata einrühren, 10 Minuten köcheln lassen.',
      'Mulden in die Sauce drücken, Eier hineinschlagen.',
      'Deckel auflegen, 8-10 Minuten garen bis Eier gestockt sind.',
      'Feta darüber bröseln, mit Koriander und Brot servieren.',
    ],
  ),
  _recipe(
    id: 'seed-15',
    title: 'Schnitzel mit Pommes',
    category: RecipeCategory.meat,
    tags: ['deutsch', 'Klassiker', 'deftig'],
    prepTime: 20, cookTime: 15, servings: 2,
    ingredients: [
      _ing('Schweineschnitzel', 2, 'Stück'),
      _ing('Ei', 2, 'Stück'),
      _ing('Paniermehl', 100, 'g'),
      _ing('Mehl', 50, 'g'),
      _ing('Kartoffeln', 600, 'g'),
      _ing('Öl (zum Frittieren)', 500, 'ml'),
      _ing('Zitrone', 1, 'Stück'),
      _ing('Salz', null, null),
      _ing('Pfeffer', null, null),
    ],
    steps: [
      'Schnitzel flach klopfen, salzen und pfeffern.',
      'Kartoffeln in Stifte schneiden, 20 Minuten in Öl bei 160°C vorfrittieren.',
      'Schnitzel in Mehl, Ei und Paniermehl wenden.',
      'In reichlich Öl 3-4 Minuten pro Seite goldbraun braten.',
      'Pommes bei 190°C knusprig fertig frittieren.',
      'Mit Zitrone servieren.',
    ],
  ),
];

int _idCounter = 0;

Recipe _recipe({
  required String id,
  required String title,
  required RecipeCategory category,
  required List<String> tags,
  required int prepTime,
  required int cookTime,
  required int servings,
  required List<Ingredient> ingredients,
  required List<String> steps,
}) {
  final now = DateTime(2026, 1, 1);
  return Recipe(
    id: id,
    title: title,
    category: category,
    tags: tags,
    prepTimeMinutes: prepTime > 0 ? prepTime : null,
    cookTimeMinutes: cookTime > 0 ? cookTime : null,
    servings: servings,
    ingredients: ingredients,
    steps: steps
        .asMap()
        .entries
        .map((e) => RecipeStep(
              id: '$id-step-${e.key}',
              stepNumber: e.key + 1,
              instruction: e.value,
            ))
        .toList(),
    createdAt: now,
    updatedAt: now,
  );
}

Ingredient _ing(String name, double? amount, String? unit) {
  _idCounter++;
  return Ingredient(
    id: 'seed-ing-$_idCounter',
    name: name,
    amount: amount,
    unit: unit,
  );
}
